⬆️: Upgrade to React 18
Fintan-contents/spa-restapi-handson pull request #13
Opened 2023-11-06 10:32 UTC by sinho-lee

## ✅ What's done

- [x] Reactのバージョンアップ v17.0.3 → v18.2.0
- [x] react-router-domのバージョンアップ v5.2.0 → v5.3.4
  - v5.3.4に上げた理由はv5.3.3からはReact v18との互換性の問題を解決したので、v5.3系の最新バージョンにしました。詳細についてはOtherのreact-router-domのURL先に記載されています。
- [x] Reactのバージョンアップによるソースコード修正
- [x] react-router-domのバージョンアップによるソースコード修正
- [x] Reactのバージョンアップによるドキュメントの修正
  - プロントエンドの確認ページ
  - ユーザーコンテクストの作成ページ
  - CSRF対策ページ
- [x] react-router-domのバージョンアップによるドキュメントの修正
  - ユーザーコンテクストの作成ページ
  - ルーティングの設定ページ

## Tests

- [x] 各画面が表示されることを打鍵テストで確認
- [x] 各機能が問題なく動くことを打鍵テストで確認

## Other (messages to reviewers, concerns, etc.)

- ReactのバージョンアップによるReactのエラーを解消するため、参考にした内容は下記の通りです。
  -  [クライアントレンダリング API への変更](https://ja.react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis)
   - [TypeScript 型定義の変更](https://ja.react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-typescript-definitions)
- react-router-domのバージョンアップによるreact-router-domのエラーを解消するため、参考にした内容は下記の通りです。
   - [Fix: make v5 Router compatible with v18 StrictMode](https://github.com/remix-run/react-router/pull/8831)
   - [BrowserRouterの問題](https://github.com/remix-run/react-router/issues/7870#issuecomment-1099884642)

2023-11-10 04:52 UTC, creature-water-valley requested changes

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
↓は恐らくこのハンズオンでは使っていないのかなと思います。
なので、削除するっていう方針になったかと思います。（アップグレードとは関係ないので、別PRで対応が良いと思います。）

>    "@testing-library/jest-dom": "^5.11.9",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.8.3",
    "@types/jest": "^26.0.20",

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/package.json
> +    "react-scripts": "^5.0.1",
元々は`"react-scripts": "4.0.3"`のようにバージョン固定していたようなので、今回のアップグレードでも`5.0.1`に固定にしておいても良いのではないかと思いました。

（ただ、元々固定にしていた理由はちょっとわかっていないので、そこは確認した方が良いかもです。）

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/src/contexts/UserContext.tsx
> +export const UserContextProvider: React.FC<Props> = ({ children }) => {
モバイルの方は、`React.PropsWithChildren`で`children`の対応をしているので、それに合わせた方が良さそうに思いました。

[React 18の対応](https://ws-4020.github.io/mobile-app-crib-notes/react-native/santoku/maintenance/enhance/expo-46-upgrade#react-18%E3%81%AE%E5%AF%BE%E5%BF%9C)

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/src/contexts/UserContext.tsx
> +      } catch(error: any) {
型ガードで判定した方が良さそうには思います。
が、特にこのハンズオンはESLintとかを入れてないので、これは許容の範囲かもしれないです。
チーム内で確認してみましょう。

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/auth/frontend/context/README.md
差分にはない箇所なので、このファイルとは関係ないですがここに記載します。

Node.jsのバージョンを現在LTSのバージョンに上げるっていう方針だったと思います。
https://fintan-contents.github.io/spa-restapi-handson/setup/install/

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
このページの最初に以下のような文章がありますが、CRAで作成したプロジェクトは`index.tsx`がReact 18対応していないようです。
なので、その点も修正を加えた状態に入れた方が良さそうです。

>実装を小さくするために、CRAで生成されたプロジェクトに次のような修正を加えた状態です。
>- 開発に使用するDockerCompose定義ファイルを追加
>- HelloWorldを表示するだけの簡易なページに変更
>- ページ変更に伴う不要ファイルの削除

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`createRoot()`メソッドを使用してアプリのルートレンダリングエントリポイントを作成できます。（参考：[createRoot](https://ja.react.dev/reference/react-dom/client/createRoot)）
参考ドキュメントでは、`ルートコンポーネント`という単語が使われていたので、それを使用
```suggestion
`createRoot()`を使用してアプリのルートコンポーネントを作成しています。（参考：[createRoot](https://ja.react.dev/reference/react-dom/client/createRoot)）
```

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`createRoot()`の引数にはDOM要素を指定します。ここでは[`Document.getElementById()`](https://developer.mozilla.org/ja/docs/Web/API/Document/getElementById)の実行結果を渡しています。
元の文章にはあった「レンダー先の」がある方がわかりやすいため
```suggestion
`createRoot()`の引数にはレンダー先のDOM要素を指定します。ここでは[`Document.getElementById()`](https://developer.mozilla.org/ja/docs/Web/API/Document/getElementById)の実行結果を渡しています。
```

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`root.render()`メソッドを使用してReactコンポーネントを指定されたルートにレンダリングします。（参考：[root.render(reactNode)](https://ja.react.dev/reference/react-dom/client/createRoot#root-render)）
DOMの方がわかりやすそうなため
```suggestion
`root.render()`メソッドを使用してReactコンポーネントを指定されたDOMにレンダリングします。（参考：[root.render(reactNode)](https://ja.react.dev/reference/react-dom/client/createRoot#root-render)）
```

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`root.render()`の引数にはReactコンポーネントを指定します。ここでは、上で説明したJSXを使用して、`<BrowserRouter>`、`<React.StrictMode>`とその子要素に`<App>`があるReact要素を定義しています。
唐突に`BrowserRouter`が出てきているので、何かしらの補足があった方が良さそうに思いました。

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +ここでの`document`は前述の`public/index.html`を指しており、そこで定義されている`<div id="root"></div>`を表すDOMに、`root.render()`に作成されているReactコンポーネントがレンダーされることになります。
「ここでの`document`」が文章構成が変わってしまったので、何を指しているのかわかりづらい気がしました。

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`root.render()`の引数にはReactコンポーネントを指定します。ここでは、上で説明したJSXを使用して、`<BrowserRouter>`、`<React.StrictMode>`とその子要素に`<App>`があるReact要素を定義しています。
というか、starter-kitには`BrowserRouter`を含めていないのでは？

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/auth/frontend/routing/README.md
恐らく、このページで`index.tsx`に`BrowserRouter`を設定する記述が必要な気がします。

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
このページで更新しているReactのドキュメントリンクは`react.dev`になっていますが、他のページなどは`reactjs.org`の方をリンク先に指定しています。

ここら辺の対応はどうするかをチーム内で検討した方が良さそうです。

2023-11-10 04:52 UTC, creature-water-valley commented on book/source/auth/frontend/routing/README.md
↓のリンクも、[v5のドキュメント](https://v5.reactrouter.com/)に飛ばしたほうが良いと思いました。
>ルーティングを実現するために、React用のルーティングライブラリである[React Router](https://reactrouter.com/)を導入します。

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/src/index.tsx
> +  <BrowserRouter>
`v5.3.2`で修正されているように見えます。
https://github.com/remix-run/react-router/releases?q=make+v5+Router+compatible+with+v18+StrictMode&expanded=true

試しに、`BrowserRouter`を`App.tsx`に移動してみましたが、正常に遷移できでそうでしたが、何か不具合ありましたか？？

2023-11-10 04:52 UTC, creature-water-valley commented on example/todo-app/frontend/package-lock.json
`@babel/plugin-proposal-decorators`など、いくつかのライブラリが`starter-kitで使用しているバージョンと違うみたいです。
このハンズオンは、starter-kitの`package-lock.json`をそのままコピーして使っているようなので、合わせた方が良さそうです。

2023-11-10 05:23 UTC, sinho-lee commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
確認後、別PRで対応します。

2023-11-10 06:20 UTC, creature-water-valley commented on example/todo-app/frontend/src/contexts/UserContext.tsx
> +export const UserContextProvider: React.FC<Props> = ({ children }) => {
でも、`example-chat`では`children: React.ReactNode;`で対応してるみたいですね。
https://github.com/Fintan-contents/example-chat/blob/master/frontend/src/chat/components/basics/Modal.tsx#L7

`example-chat`に合わせた方が良さそうなので、この指摘は取り下げます。

2023-11-10 06:29 UTC, sinho-lee commented on example/todo-app/frontend/src/contexts/UserContext.tsx
> +      } catch(error: any) {
この件について浦上さんに確認してもらいました。
`contextValue`は共通の部分でもあり、他のところでも`any`を使用しているので、特に問題はないとのことでした。

2023-11-10 06:43 UTC, creature-water-valley commented on book/source/auth/frontend/routing/README.md
> +        <Route path="/signup">
ドキュメントから`exact`を削除していますが、ドキュメントの方が合っていて、exampleの方に`exact`が付いていないのが間違いでは？？

2023-11-10 07:01 UTC, creature-water-valley commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
↓とかで使ってそうですね。
https://github.com/Fintan-contents/spa-restapi-handson/blob/master/example/todo-app/frontend/src/validation/Validation.test.tsx

ただ、`devDependecies`に移動した方が良さそうですが。

2023-11-10 07:25 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
`npx create-react-app my-app --template typescript`コマンドで最新版を作成してみましたが、React 18を対応しています。`index.tsx`の対応は不要ではないでしょうか。

2023-11-10 07:33 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
`ReactDOM`があったので、対応していないと勘違いしてしまいました。。。
確かに、`createRoot`は使ってますね。

ただ、CRAをそのまま使うっていうことなので、このリポジトリの`index.tsx`も↓のように修正した方が良いかもしれませんね。

```tsx
import ReactDOM from 'react-dom/client';

const root = ReactDOM.createRoot(
```

2023-11-10 07:38 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
承知いたしました。
上記のように対応いたします。

2023-11-10 07:41 UTC, creature-water-valley commented on example/todo-app/frontend/src/index.tsx
> +  <BrowserRouter>
@sinho-lee これ先に確認してもらった方が良いかもです。
他の指摘は修正しなくても良くなるかもしれません。

2023-11-10 07:55 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
> +`root.render()`メソッドを使用してReactコンポーネントを指定されたルートにレンダリングします。（参考：[root.render(reactNode)](https://ja.react.dev/reference/react-dom/client/createRoot#root-render)）
[上記のコメント](https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1388818109)の内容と同様に修正してみましたが、いかがでしょうか。（「メソッドを」を削除）
```suggestion
`root.render()`を使用してReactコンポーネントを指定されたDOMにレンダリングします。（参考：[root.render(reactNode)](https://ja.react.dev/reference/react-dom/client/createRoot#root-render)）
```

2023-11-10 08:19 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
> +`root.render()`の引数にはReactコンポーネントを指定します。ここでは、上で説明したJSXを使用して、`<BrowserRouter>`、`<React.StrictMode>`とその子要素に`<App>`があるReact要素を定義しています。
> 唐突に`BrowserRouter`が出てきているので、何かしらの補足があった方が良さそうに思いました。というか、starter-kitには`BrowserRouter`を含めていないのでは？

React 18にアップデートした後のソースコードをそのまま貼ってしまいました。作業の流れとしてまだ`react-router-dom`を使用していないので、削除し、「ルーティングの設定」ページに`BrowserRouter`を追加したソースコードを記載します。

2023-11-13 00:15 UTC, sinho-lee commented on example/todo-app/frontend/package.json
> +    "react-scripts": "^5.0.1",
対応Commit: 798798b4030f4cdd750e25e2eaeff210c06ae318
バージョン固定しました。
固定されていた理由は構築する時の[react-script](https://github.com/facebook/create-react-app/blob/f92c37a6e6636ed1650ffd976c6881f59b1be803/packages/react-scripts/package.json#L3C1-L3C1)のバージョンが固定されていたためかと思います。

2023-11-13 00:16 UTC, sinho-lee commented on book/source/auth/frontend/context/README.md
修正漏れでした。修正しました。
対応Commit: 23ddd8094b3ae99e2a7005db281d63e199cdf9a4

2023-11-13 00:22 UTC, creature-water-valley commented on book/source/auth/frontend/context/README.md
Nodeをvupすると恐らくnpmのバージョンも上がる気がするので、package-lock.jsonにも更新が入りそうな気がします。

2023-11-13 01:00 UTC, sinho-lee commented on example/todo-app/frontend/src/index.tsx
> +  <BrowserRouter>
何回も再確認してみましたが、確かに問題なかったので、元に戻します。
対応Commit: ad824dfda58fdc92a4d75bc4baf44feedc63ee79

2023-11-13 01:02 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1390531061 で対応しました。

2023-11-13 01:02 UTC, sinho-lee commented on book/source/auth/frontend/routing/README.md
https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1390531061 で対応しました。

2023-11-13 01:03 UTC, sinho-lee commented on book/source/auth/frontend/routing/README.md
対応Commit: 92f52189341e146e407f9f37b590bd99e0c61684

2023-11-13 01:24 UTC, sinho-lee commented on book/source/auth/frontend/routing/README.md
> +        <Route path="/signup">
削除してましたので、元に戻します。
対応Commit: a1e02f37f4bb5753f627c266e5aec7fe0554b10e, b86ab9b36645fba6393d395a4c744100352f969f

2023-11-13 01:29 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
対応Commit: 233eb8274d5ba6a0567289c8561b4e414b019477, 194a14abf51e26a85303954462137c65d45ea93a

2023-11-13 02:07 UTC, sinho-lee commented on book/source/auth/frontend/context/README.md
対応Commit
 - todo-app: 5bf1fd70f75dcb10fa87b2a393e4b159a3d9e9ed
 - starter-kit: 8f8e8fddcb67d5888c3fb728b28866e91e5dee69
 - book: 949060069900906cc5b8bd0c23464196ba03c4c6

2023-11-13 02:24 UTC, sinho-lee commented on example/todo-app/frontend/package-lock.json
https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1390560668 で対応しました。

2023-11-13 04:46 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
> +ここでの`document`は前述の`public/index.html`を指しており、そこで定義されている`<div id="root"></div>`を表すDOMに、`root.render()`に作成されているReactコンポーネントがレンダーされることになります。
対応Commit: 4ff62c82ed16e264d317b8f472062220e7753011, d177c39eaa9d5361e237240c07a005522a8f4537

2023-11-13 05:50 UTC, creature-water-valley commented on starter-kit/frontend/package.json
> +    "react-scripts": "^5.0.1",
`"react-scripts": "^5.0.1",`がバージョン固定になっていないようです。

2023-11-13 05:51 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
コメントに記載されているリンクは違う対応みたいです？

2023-11-13 06:23 UTC, sinho-lee commented on book/source/todo-project/frontend/README.md
> [#13 (comment)](https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1390531061) で対応しました。

失礼いたしました。間違えてコメントしました。

本日、朝会後Reactの最新ドキュメントのリンクについて浦上さんと会話しました。
PRは今のPRでも別PRでも問題ないとのことですが、一旦現在プロジェクトで使ってる箇所をリストアップして明日の朝会で確認後、対応することになりました。

2023-11-13 06:36 UTC, sinho-lee commented on starter-kit/frontend/package.json
> +    "react-scripts": "^5.0.1",
修正漏れでした。バージョン固定しました。
対応Commit: 9fffbb6c0d286f28361bf2e68191d8e86f2ddc8f

2023-11-13 08:05 UTC, sinho-lee commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
対応Commit
  - todo-app: 3c29615fb8844df338364a1cd8a06b5c21d9e964
  - starter-kit: d2589835fe35df21614946eb9bde804b5c4a44dc

2023-11-13 08:25 UTC, creature-water-valley commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
[フロントエンド開発プロジェクトを確認する](https://fintan-contents.github.io/spa-restapi-handson/todo-project/frontend/#%E3%83%95%E3%83%AD%E3%83%B3%E3%83%88%E3%82%A8%E3%83%B3%E3%83%89%E9%96%8B%E7%99%BA%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B)の以下の部分にCRAからの変更点を追記した方が良いかもしれません。

>実装を小さくするために、CRAで生成されたプロジェクトに次のような修正を加えた状態です。
開発に使用するDockerCompose定義ファイルを追加
HelloWorldを表示するだけの簡易なページに変更
ページ変更に伴う不要ファイルの削除

2023-11-13 08:29 UTC, ghost commented on book/source/auth/frontend/context/README.md
> +React v18からpropsを定義する際にchildrenプロパティを明示的に列挙する必要があるので、`Props`型を定義します。
💭 `PropsWithChildren`もあるので、言及してあげてもいい気がします。もしくはそっちに変えるか。

2023-11-13 08:29 UTC, in-a-paddy commented on book/source/auth/frontend/context/README.md
> +          <Route exact path="/board">
❓ v6でデフォルトの振る舞いが変わっているようではあるのですが、v6の動作と合わせるためにあえて追加していますか？

2023-11-13 08:29 UTC, in-a-paddy commented on book/source/auth/frontend/routing/README.md
> +「登録する」ボタンがクリックされたら`/signup`URLへ遷移するように、`Link`コンポーネントを使用します。`to`プロパティには、遷移先のURLを指定します。（参考：[Link](https://v5.reactrouter.com/web/api/Link)）
💭 元と同じページがあるような気がするので、Quick Startへのリンクにしておいてもいいんじゃないかと。
https://v5.reactrouter.com/web/guides/quick-start/1st-example-basic-routing

2023-11-14 00:14 UTC, sinho-lee commented on book/source/auth/frontend/context/README.md
> +React v18からpropsを定義する際にchildrenプロパティを明示的に列挙する必要があるので、`Props`型を定義します。
https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1388757124 このコメントのように`examepl-chat`では`children: React.ReactNode;`で対応しているので、`examepl-chat`の対応と合わせました。

2023-11-14 00:55 UTC, sinho-lee commented on book/source/auth/frontend/context/README.md
> +          <Route exact path="/board">
このプロジェクトはv5なので`exact`を付けました。（v6からは`exact`を対応しないようです。）

2023-11-14 01:17 UTC, sinho-lee commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
対応Commit: 6337631158127c2d6153a1f5b8ed91c6482348d4, 6f103a45f40bfc780d6ca0ad5bae88457474044c

2023-11-14 01:18 UTC, sinho-lee commented on book/source/auth/frontend/routing/README.md
> +「登録する」ボタンがクリックされたら`/signup`URLへ遷移するように、`Link`コンポーネントを使用します。`to`プロパティには、遷移先のURLを指定します。（参考：[Link](https://v5.reactrouter.com/web/api/Link)）
対応Commit: cc8406eff08c6382715b728fbdae0941b40b33d1

2023-11-14 05:25 UTC, creature-water-valley commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
細かくパッケージ名を記載しても見づらい気がするので、「アプリの実行時には使用しないライブラリを〜」のようにまとめてしまった方が良さそうに思いました。

2023-11-14 05:35 UTC, sinho-lee commented on example/todo-app/frontend/package.json
>      "@types/jest": "^26.0.20",
> 細かくパッケージ名を記載しても見づらい気がするので、「アプリの実行時には使用しないライブラリを〜」のようにまとめてしまった方が良さそうに思いました。

上記のように修正しました。
対応Commit: b01444a253dbc1994538fa63efb038c4a667bd21

2023-11-15 02:08 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
> +`root.render()`の引数にはReactコンポーネントを指定します。ここでは、上で説明したJSXを使用して、`<BrowserRouter>`、`<React.StrictMode>`とその子要素に`<App>`があるReact要素を定義しています。
↓のコメントに記載しているコミットで、`index.tsx`には`BrowserRouter`は利用しなくなったので、このディスカッションもクローズします。
- https://github.com/Fintan-contents/spa-restapi-handson/pull/13#discussion_r1390531061

2023-11-15 02:15 UTC, creature-water-valley commented on book/source/todo-project/frontend/README.md
別PRで対応する方針となったため、このディスカッションはクローズします。

2023-11-15 02:20 UTC, creature-water-valley approved these changes

2023-11-15 07:58 UTC, in-a-paddy commented on book/source/auth/frontend/context/README.md
> +          <Route exact path="/board">
5.2.0 → 5.3.4のアップグレードと関係はありますか？

2023-11-15 08:01 UTC, sinho-lee commented on book/source/auth/frontend/context/README.md
> +          <Route exact path="/board">
関係ないです。他のページと合わせるために`exact`を追加しました。

2023-11-15 08:24 UTC, in-a-paddy commented on book/source/auth/frontend/routing/README.md
> -
❓ この行って消す必要ありますか？

2023-11-15 08:33 UTC, sinho-lee commented on book/source/auth/frontend/routing/README.md
> -
`BrowserRouter`に関する文章を元に戻しました。
Commit: 2831d038c11165fbf72da7667872cc14aad9e3cf

2023-11-16 07:46 UTC, in-a-paddy commented on book/source/auth/frontend/routing/README.md
> +次に、URLによるルーティングを行うため、`Switch`コンポーネントと`Route`コンポーネントを使用します。（参考：[Switch](https://v5.reactrouter.com/web/api/Switch)、[Route](https://v5.reactrouter.com/web/api/Route)）
⚠ 指摘漏れてましたが、ここもQuick Startを参照するままで良いのではないかと。

```suggestion
次に、URLによるルーティングを行うため、`Switch`コンポーネントと`Route`コンポーネントを使用します。（参考：[Basic Routing | React Router](https://v5.reactrouter.com/web/guides/quick-start/1st-example-basic-routing)）
```

2023-11-16 08:03 UTC, in-a-paddy approved these changes

2023-11-16 08:08 UTC, merged